### ISSUE TITLE
Sometring is wrong with the -Strace option

### ISSUE THREAD

**Issue by diegoortega** [delt0r/msms#4] opened 2012-10-02 18:32 UTC
I am trying to use the -Strace option but the option is not working for me on the newest version of the software (msms3.2rc-b75.zip). It worked well with a previous version of the software (msms3.2rc-b13.zip). The format of the file I am using for my tests is:

0.024   5e-05
0.023975    0.0001
0.02395 0.0001
0.023925    0.00015
0.0239  0.0001
0.023875    0.00015
0.02385 0.00025
0.023825    0.0004
0.0238  0.0004
0.023775    0.00025
0.02375 0.00035
0.023725    0.00095
...

And the command line I used to test the code is:

java -jar msms.jar 10 1 -t 48 -r 40 100000 -N 10000 -Sp 0 -Strace Trajectory.txt

For the previous version of the software, I got:

ms 10 1 -t 48 -r 40 100000 -N 10000 -Sp 0 -Strace Trajectory.txt 
0x15a0a7412d39c843

//
segsites: 121
positions: 0.03720 0.04518 0.05564 0.06069 0.06483 0.06883 0.07453 0.08114 0.08459 0.09183 0.09976 0.10088 0.10574 0.11257 0.12125 0.13568 0.13954 0.15195 0.15226 0.16286 0.18697 0.18829 0.19032 0.20555 0.20663 0.22010 0.22811 0.23506 0.25507 0.25645 0.26130 0.26841 0.27090 0.27935 0.28833 0.30388 0.32378 0.32572 0.39063 0.39716 0.40005 0.40134 0.40516 0.40580 0.42593 0.50681 0.52848 0.52890 0.53348 0.54213 0.55398 0.56652 0.57135 0.57178 0.60347 0.62405 0.62870 0.62903 0.64188 0.64240 0.66279 0.67506 0.67591 0.68129 0.68972 0.69125 0.69625 0.69748 0.71601 0.71679 0.71694 0.71848 0.72051 0.72539 0.73170 0.73382 0.73779 0.74074 0.74434 0.74508 0.75122 0.75190 0.75427 0.75613 0.75641 0.75894 0.75951 0.76352 0.76772 0.78748 0.79321 0.79473 0.79573 0.79708 0.79967 0.80294 0.80335 0.80467 0.80596 0.81641 0.83634 0.83971 0.86569 0.86820 0.87684 0.89766 0.92203 0.94169 0.96091 0.96200 0.96794 0.96957 0.97217 0.97368 0.97786 0.98123 0.98488 0.98651 0.98676 0.98860 0.99119 
0010000001000011010000000000011000000000010010010000110100000100011001010000001111100001010000111100000000010000010000001
0010000000000011100100010010100000000000101000100111001001001001101101000000001111100000010000110100000000000110001010010
1001010000011000010011000000000100100001101100010000000100001000000010100001110000001110100100110100000100000001000101101
1010000001000011100100100001000000011001101100000000000110010011101101000000001111100000010000110100000000000000010000001
0010000001000011100100100001000000011001101000000000000110010001101101001100001110110000010000110101000001001000000101101
0010000001000011100100100001000000011001101000000000000110010001101101001100001110110000010000110101000001001000000101101
0000101100000011101100001100001010000010101000000001000000101000000010000001110000001110101011000000100000100110001010010
0010000001000011010000000000011000000000010010010000110100000100011001010000001111100001010000111100000000010000010000001
0000000000000111100100000000000001000100010011010000110000101000000010000001110000001110101011000000100000000000010000001
0100101110100011100100000000011000000000010010011000110100000100001001000010001111100000010000110110011010010000110000001

And for the newest version, I got:

ms 10 1 -t 48 -r 40 100000 -N 10000 -Sp 0 -Strace Trajectory.txt  [3.2rc Build:74]
0x746b5e94099e0450

Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 1
    at at.mabs.simulators.ReaderSelection.putFrequency(ReaderSelection.java:168)
    at at.mabs.simulators.ReaderSelection.forwardSimulator(ReaderSelection.java:120)
    at at.mabs.model.selection.SelectionData.runSelectionSimulation(SelectionData.java:169)
    at at.mabs.model.ModelHistroy.simulateSelection(ModelHistroy.java:377)
    at at.MSLike.run(MSLike.java:299)
    at at.MSLike.runThreads(MSLike.java:424)
    at at.MSLike.runMe(MSLike.java:191)
    at at.MSLike.main(MSLike.java:541)
    at at.MSLike.main(MSLike.java:585)

Can you help me with that?
Thanks

**Comment by delt0r** [comment] 2012-10-03 12:30
I will have a look. Its seems to be a regression. I probably won't get to this till Friday however.

**Comment by delt0r** [comment] 2012-10-16 13:09
We are still looking into this. Currently it appears to be a format error of the input file. You need frequencies for both alleles need to be specified.

**Comment by delt0r** [comment] 2013-05-14 15:48
This is now fixed. But the format has changed. You need the frequency of both alleles. ie same format as the -oTrace option.

**Closed as completed by delt0r** 2013-05-14 15:48 UTC
Labels: bug
